#!/usr/bin/env python3
"""Keep Codex's reusable harness aligned with Claude Code without changing Claude.

Claude Code is always the read-only source. Portable resources are linked so
edits become visible immediately. Host-specific resources are translated into
Codex-owned generated files.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
import os
from pathlib import Path
import shutil
import sys
from typing import Any


MANAGED_AGENT_HEADER = "# Generated by ~/.claude/codex/harness-sync/sync.py from Claude Code. Do not edit."


class Sync:
    def __init__(self, source: Path, codex_home: Path, agents_home: Path, *, check: bool, adopt: bool):
        self.source = source.resolve()
        self.codex_home = codex_home.resolve()
        self.agents_home = agents_home.resolve()
        self.check = check
        self.adopt = adopt
        self.changed: list[str] = []
        self.ok: list[str] = []
        self.conflicts: list[str] = []
        self.desired_links: dict[str, str] = {}
        stamp = dt.datetime.now().strftime("%Y%m%d-%H%M%S")
        self.backup_root = self.codex_home / "harness-sync" / "backups" / stamp
        self.state_path = self.codex_home / "harness-sync" / "state.json"
        self.previous_state = self._read_json(self.state_path, default={})

    @staticmethod
    def _read_json(path: Path, default: Any) -> Any:
        try:
            return json.loads(path.read_text())
        except (FileNotFoundError, json.JSONDecodeError):
            return default

    @staticmethod
    def _lexists(path: Path) -> bool:
        return os.path.lexists(path)

    @staticmethod
    def _link_target(path: Path) -> Path:
        raw = Path(os.readlink(path))
        return (path.parent / raw).resolve() if not raw.is_absolute() else raw.resolve()

    def _backup(self, path: Path, label: str) -> None:
        target = self.backup_root / label
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(path), str(target))
        self.changed.append(f"backed up {path} -> {target}")

    def _ensure_symlink(self, source: Path, destination: Path, backup_label: str) -> None:
        source = source.resolve()
        self.desired_links[str(destination)] = str(source)
        if destination.is_symlink() and self._link_target(destination) == source:
            self.ok.append(f"linked {destination}")
            return

        if self._lexists(destination):
            if not self.adopt:
                self.conflicts.append(f"{destination} exists and is not the desired link")
                return
            if self.check:
                self.changed.append(f"would back up and replace {destination}")
                return
            self._backup(destination, backup_label)

        if self.check:
            self.changed.append(f"would link {destination} -> {source}")
            return
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.symlink_to(source, target_is_directory=source.is_dir())
        self.changed.append(f"linked {destination} -> {source}")

    def sync_skills(self) -> None:
        source_root = self.source / "skills"
        target_root = self.agents_home / "skills"
        self._ensure_symlink(source_root, target_root, "agents-skills")

    @staticmethod
    def _toml_string(value: str) -> str:
        # JSON strings are valid TOML basic strings for the characters emitted here.
        return json.dumps(value, ensure_ascii=False)

    def sync_agents(self) -> None:
        desired: set[Path] = set()
        for source_agent in sorted((self.source / "agents").glob("*.md")):
            name = source_agent.stem
            description = f"Bridge to the shared Claude Code agent definition: {name}"
            destination = self.codex_home / "agents" / f"{name}.toml"
            desired.add(destination)
            instructions = (
                f"Read and follow the complete agent definition at {source_agent}. "
                "Treat that file as the source of truth for this task. "
                "Do not edit the source definition."
            )
            rendered = "\n".join(
                [
                    MANAGED_AGENT_HEADER,
                    f"# Source: {source_agent}",
                    f"name = {self._toml_string(name)}",
                    f"description = {self._toml_string(description)}",
                    f"developer_instructions = {self._toml_string(instructions)}",
                    "",
                ]
            )
            self._ensure_generated(destination, rendered, f"agents/{destination.name}", MANAGED_AGENT_HEADER)

        agents_dir = self.codex_home / "agents"
        if agents_dir.exists():
            for candidate in agents_dir.glob("*.toml"):
                if candidate in desired:
                    continue
                try:
                    managed = candidate.read_text().startswith(MANAGED_AGENT_HEADER)
                except OSError:
                    managed = False
                if managed:
                    if self.check:
                        self.changed.append(f"would remove stale generated agent {candidate}")
                    else:
                        candidate.unlink()
                        self.changed.append(f"removed stale generated agent {candidate}")

    def _ensure_generated(self, destination: Path, rendered: str, backup_label: str, marker: str) -> None:
        try:
            current = destination.read_text()
        except (FileNotFoundError, IsADirectoryError):
            current = None
        if current == rendered:
            self.ok.append(f"generated {destination}")
            return
        if self._lexists(destination) and (current is None or marker not in current):
            if not self.adopt:
                self.conflicts.append(f"{destination} exists and is not managed by the syncer")
                return
            if self.check:
                self.changed.append(f"would back up and regenerate {destination}")
                return
            self._backup(destination, backup_label)
        if self.check:
            self.changed.append(f"would generate {destination}")
            return
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(rendered)
        self.changed.append(f"generated {destination}")

    def clean_stale_links(self) -> None:
        old_links = self.previous_state.get("links", {})
        for destination_text, source_text in old_links.items():
            if destination_text in self.desired_links:
                continue
            destination = Path(destination_text)
            if destination.is_symlink() and self._link_target(destination) == Path(source_text).resolve():
                if self.check:
                    self.changed.append(f"would remove stale link {destination}")
                else:
                    destination.unlink()
                    self.changed.append(f"removed stale link {destination}")

    def write_state(self) -> None:
        if self.check or self.conflicts:
            return
        state = {
            "source": str(self.source),
            "links": self.desired_links,
            "last_sync": dt.datetime.now(dt.timezone.utc).isoformat(),
            "boundaries": [
                "AGENTS.md is a Codex entry-point symlink to Claude's CLAUDE.md",
                "the bridge maps file structure only and never interprets harness instructions",
                "Claude hooks are not synchronized",
                "permissions and sandbox policy are Codex-owned",
                "plugin enablement, history, jobs, runtime state, and memories are not synchronized",
                "MCP is not rewritten automatically; existing Codex config remains authoritative",
            ],
        }
        self.state_path.parent.mkdir(parents=True, exist_ok=True)
        self.state_path.write_text(json.dumps(state, ensure_ascii=False, indent=2) + "\n")

    def run(self) -> int:
        if not self.source.is_dir():
            print(f"Claude source not found: {self.source}", file=sys.stderr)
            return 2
        self.sync_skills()
        self.sync_agents()
        self.clean_stale_links()
        self.write_state()

        for item in self.changed:
            print(f"CHANGE {item}")
        for item in self.conflicts:
            print(f"CONFLICT {item}", file=sys.stderr)
        print(
            f"Summary: {len(self.changed)} change(s), {len(self.ok)} already current, "
            f"{len(self.conflicts)} conflict(s)."
        )
        if self.conflicts:
            return 2
        if self.check and self.changed:
            return 1
        return 0


def main() -> int:
    home = Path.home()
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=home / ".claude")
    parser.add_argument("--codex-home", type=Path, default=home / ".codex")
    parser.add_argument("--agents-home", type=Path, default=home / ".agents")
    parser.add_argument("--check", action="store_true", help="report drift without writing")
    parser.add_argument("--adopt", action="store_true", help="back up and replace conflicting Codex-owned targets")
    args = parser.parse_args()
    return Sync(args.source, args.codex_home, args.agents_home, check=args.check, adopt=args.adopt).run()


if __name__ == "__main__":
    raise SystemExit(main())
